"use client";
import {useEffect,useState} from "react";
import {applySrTheme,type SrTheme} from "../_components/ThemeController";
type Prefs={app_theme:SrTheme;collective_stats_opt_in:boolean;strategy_preset:"popular"|"comfort"|"premium"|"custom";max_pickup_km:number;max_pickup_minutes:number;min_per_km:number;min_per_minute:number;min_per_hour:number;};
function presetName(v?:string){return v==="popular"?"Popular":v==="comfort"?"Conforto":v==="premium"?"Premium":"Personalizado";}
export default function ConfiguracoesPage(){const[prefs,setPrefs]=useState<Prefs|null>(null);const[msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/v1/preferences",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(j=>setPrefs(j?.preferences??null)).catch(()=>undefined)},[]);
 async function save(patch:Record<string,unknown>){setMsg("Salvando…");const r=await fetch("/api/v1/preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const j=r.ok?await r.json():null;if(j?.preferences){setPrefs(j.preferences);setMsg("Salvo.")}else setMsg("Não foi possível salvar.");}
 return <div className="sr023Page"><section className="sr023Hero"><div><h1>Configurações</h1><p>Ajuste o Sr. Rotas do seu jeito.</p></div><article className="sr023Ready"><div className="sr023IconBox good">✓</div><div><strong>Preferências sincronizadas</strong><span>{presetName(prefs?.strategy_preset)} · Web e Android usam a mesma base</span></div><b>ONLINE</b></article><div className="sr023ThemeRow">{(["auto","light","dark"] as SrTheme[]).map(t=><button key={t} className={prefs?.app_theme===t?"active":""} onClick={()=>{applySrTheme(t);save({app_theme:t}).catch(()=>undefined)}}>{t==="auto"?"Automático":t==="light"?"Claro":"Escuro"}</button>)}</div></section>
 <section className="sr023Grid"><article className="sr023Tile"><i className="blue">☷</i><div><h2>Estratégia e HUD</h2><p>Perfil {presetName(prefs?.strategy_preset)} e metas sincronizadas.</p></div></article><article className="sr023Tile"><i className="teal">⌖</i><div><h2>Busca</h2><p>{prefs?`${prefs.max_pickup_km} km / ${prefs.max_pickup_minutes} min`:"Carregando…"}</p></div></article><article className="sr023Tile"><i className="orange">☼</i><div><h2>Aparência</h2><p>Tema Automático, Claro ou Escuro.</p></div></article><article className="sr023Tile"><i className="purple">✦</i><div><h2>Base coletiva</h2><p>{prefs?.collective_stats_opt_in?"Participando":"Participação desativada"}</p></div></article></section>
 <section className="sr023Panel"><h2>Perfil de serviço</h2><div className="sr023ChoiceRow">{(["popular","comfort","premium"] as const).map(v=><button key={v} className={prefs?.strategy_preset===v?"active":""} onClick={()=>save({strategy_preset:v}).catch(()=>undefined)}>{presetName(v)}</button>)}</div>{prefs?<div className="sr023Metrics"><span><small>R$/km</small><b>{prefs.min_per_km}</b></span><span><small>R$/min</small><b>{prefs.min_per_minute}</b></span><span><small>R$/h</small><b>{prefs.min_per_hour}</b></span></div>:null}<label className="sr023Toggle"><input type="checkbox" checked={Boolean(prefs?.collective_stats_opt_in)} onChange={e=>save({collective_stats_opt_in:e.target.checked}).catch(()=>undefined)}/><span><strong>Participar da base coletiva</strong><small>Compartilha somente dados agregados/anonimizados conforme a política atual.</small></span></label><small className="sr023Save">{msg}</small></section></div>;
}
