begin;

create table if not exists public.mcp_access_tokens (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  name text not null default 'Integração MCP',
  token_hash text not null unique,
  token_prefix text not null,
  revoked boolean not null default false,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists mcp_access_tokens_driver_idx
  on public.mcp_access_tokens(driver_id, revoked, created_at desc);

alter table public.mcp_access_tokens enable row level security;

create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  driver_id uuid references public.drivers(id) on delete set null,
  request_id uuid not null default gen_random_uuid(),
  source text not null default 'sr_rotas_app',
  model text not null default 'unknown',
  status text not null check (status in ('success','error')),
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  offer_count integer not null default 0,
  duration_ms integer not null default 0,
  error_code text,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_logs_driver_created_idx
  on public.ai_usage_logs(driver_id, created_at desc);

alter table public.ai_usage_logs enable row level security;

comment on table public.mcp_access_tokens is
  'Chaves MCP por motorista. O segredo em texto puro nunca é armazenado; somente SHA-256 e prefixo de identificação.';

comment on table public.ai_usage_logs is
  'Telemetria de custo da IA própria. Não armazena a pergunta nem a resposta; somente modelo, tokens, duração e status.';

-- Como nas demais tabelas do Alpha, nenhuma policy pública.
-- Android e clientes MCP passam pelo backend service_role.
commit;
