-- Sr. Rotas Radar Contextual — POI Resolver v1
-- ADDITIVE ONLY. Requires Block 03 (`sr_radar_pois` + nullable sr_event_opportunities.poi_id).
begin;

create table if not exists public.sr_radar_poi_aliases (
  id bigint generated by default as identity primary key,
  poi_id uuid not null references public.sr_radar_pois(id) on delete cascade,
  alias text not null,
  normalized_alias text not null,
  source text,
  created_at timestamptz not null default now(),
  unique (poi_id, normalized_alias)
);

create index if not exists sr_radar_poi_aliases_normalized_idx
  on public.sr_radar_poi_aliases(normalized_alias);

create table if not exists public.sr_radar_poi_resolution_log (
  id bigint generated by default as identity primary key,
  event_id uuid references public.sr_event_opportunities(id) on delete set null,
  poi_id uuid references public.sr_radar_pois(id) on delete set null,
  decision text not null,
  score numeric(6,4),
  name_score numeric(6,4),
  distance_m integer,
  address_score numeric(6,4),
  reasons jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  check (decision in ('linked','created','review','skipped'))
);

create index if not exists sr_radar_poi_resolution_event_idx
  on public.sr_radar_poi_resolution_log(event_id, created_at desc);

create index if not exists sr_radar_poi_resolution_poi_idx
  on public.sr_radar_poi_resolution_log(poi_id, created_at desc);

alter table public.sr_radar_poi_aliases enable row level security;
alter table public.sr_radar_poi_resolution_log enable row level security;

revoke all on table public.sr_radar_poi_aliases from public,anon,authenticated;
revoke all on table public.sr_radar_poi_resolution_log from public,anon,authenticated;

grant select,insert,update,delete on table public.sr_radar_poi_aliases to service_role;
grant select,insert,update,delete on table public.sr_radar_poi_resolution_log to service_role;
grant usage,select on sequence public.sr_radar_poi_aliases_id_seq to service_role;
grant usage,select on sequence public.sr_radar_poi_resolution_log_id_seq to service_role;

comment on table public.sr_radar_poi_aliases is
  'Aliases observados para POIs canônicos do Radar. Não duplicam o POI.';
comment on table public.sr_radar_poi_resolution_log is
  'Auditoria das decisões Event -> POI. REVIEW nunca cria associação automática.';

commit;
