begin;

create extension if not exists pgcrypto;

create table if not exists public.drivers (
  id uuid primary key default gen_random_uuid(),
  display_name text not null default 'Motorista',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.driver_devices (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  name text not null default 'Android',
  token_hash text not null unique,
  revoked boolean not null default false,
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.driver_preferences (
  driver_id uuid primary key references public.drivers(id) on delete cascade,
  min_per_km numeric(10,2) not null default 1.80,
  min_per_hour numeric(10,2) not null default 35.00,
  cost_per_km numeric(10,2) not null default 0.85,
  timezone text not null default 'America/Sao_Paulo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ride_offers (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  device_id uuid not null references public.driver_devices(id) on delete cascade,
  platform text not null default 'uber',
  observed_at timestamptz not null default now(),
  source_package text not null default '',
  capture_method text not null default 'unknown',
  raw_text text not null default '',
  fare numeric(12,2) not null check (fare > 0),
  pickup_km numeric(10,2),
  trip_km numeric(10,2),
  total_km numeric(10,2),
  pickup_minutes integer,
  trip_minutes integer,
  total_minutes integer,
  per_km numeric(12,2),
  per_hour numeric(12,2),
  estimated_cost numeric(12,2),
  estimated_profit numeric(12,2),
  verdict text not null default 'regular' check (verdict in ('boa','regular','ruim')),
  parser_version text not null default 'unknown',
  dedupe_key text not null,
  created_at timestamptz not null default now(),
  unique(device_id, dedupe_key)
);

create index if not exists ride_offers_driver_observed_idx
  on public.ride_offers(driver_id, observed_at desc);
create index if not exists ride_offers_driver_verdict_idx
  on public.ride_offers(driver_id, verdict, observed_at desc);
create index if not exists ride_offers_driver_platform_idx
  on public.ride_offers(driver_id, platform, observed_at desc);

create table if not exists public.mcp_tool_audit_logs (
  id bigint generated by default as identity primary key,
  driver_id uuid references public.drivers(id) on delete set null,
  client_id text not null default 'unknown',
  tool_name text not null,
  status text not null check (status in ('success','error')),
  duration_ms integer not null default 0,
  argument_hash text not null,
  error_code text,
  created_at timestamptz not null default now()
);

alter table public.drivers enable row level security;
alter table public.driver_devices enable row level security;
alter table public.driver_preferences enable row level security;
alter table public.ride_offers enable row level security;
alter table public.mcp_tool_audit_logs enable row level security;

-- MVP: nenhuma policy pública. O backend usa somente service_role.
-- Antes de adicionar login direto pelo app, criar policies específicas por auth.uid().

commit;
