begin;

create table if not exists public.sr_event_opportunities (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  external_id text not null,
  event_type text not null default 'event',
  name text not null,
  venue_name text,
  address text,
  city text,
  state text,
  country_code text,
  lat double precision not null,
  lng double precision not null,
  starts_at timestamptz not null,
  expected_end_at timestamptz not null,
  egress_start_at timestamptz not null,
  egress_end_at timestamptz not null,
  source_url text,
  confidence numeric(5,4) not null default 0.5000,
  end_time_source text not null default 'estimated',
  status text not null default 'active',
  last_verified_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, external_id),
  check (lat between -90 and 90),
  check (lng between -180 and 180),
  check (confidence between 0 and 1),
  check (event_type in ('event','music','sports','theatre','fair_convention','family','airport','bus_terminal','mall','cultural','mobility_hub')),
  check (end_time_source in ('source','estimated')),
  check (status in ('active','expired','cancelled')),
  check (expected_end_at >= starts_at),
  check (egress_end_at >= egress_start_at)
);

create index if not exists sr_event_opportunities_active_egress_idx
  on public.sr_event_opportunities(status, egress_start_at, egress_end_at);
create index if not exists sr_event_opportunities_start_idx
  on public.sr_event_opportunities(starts_at);
create index if not exists sr_event_opportunities_location_idx
  on public.sr_event_opportunities(lat, lng);
create index if not exists sr_event_opportunities_source_verified_idx
  on public.sr_event_opportunities(source, last_verified_at desc);

create table if not exists public.sr_radar_source_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  centers_checked integer not null default 0,
  fetched_count integer not null default 0,
  saved_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  check (status in ('ok','error','skipped')),
  check (centers_checked >= 0),
  check (fetched_count >= 0),
  check (saved_count >= 0)
);

create index if not exists sr_radar_source_runs_source_created_idx
  on public.sr_radar_source_runs(source, created_at desc);

alter table public.sr_event_opportunities enable row level security;
alter table public.sr_radar_source_runs enable row level security;

revoke all on table public.sr_event_opportunities from public, anon, authenticated;
revoke all on table public.sr_radar_source_runs from public, anon, authenticated;
grant select, insert, update, delete on table public.sr_event_opportunities to service_role;
grant select, insert, update, delete on table public.sr_radar_source_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.sr_event_opportunities is
  'Oportunidades temporais normalizadas pelo Sr. Rotas Radar. Eventos e janelas de saída não garantem demanda nem corrida.';
comment on column public.sr_event_opportunities.expected_end_at is
  'Fim informado pela fonte ou estimado deterministicamente; end_time_source indica a origem.';
comment on column public.sr_event_opportunities.egress_start_at is
  'Início da janela estimada de saída do público, usada apenas como sinal contextual.';
comment on table public.sr_radar_source_runs is
  'Saúde das coletas automáticas do Sr. Rotas Radar por fonte.';

commit;
