begin;

create table if not exists public.historical_import_access (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  enabled boolean not null default true,
  added_by_driver_id uuid references public.drivers(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint historical_import_access_email_normalized check (email = lower(trim(email)))
);

insert into public.historical_import_access (email, enabled)
values ('contato@bigcorps.com.br', true)
on conflict (email) do update set enabled = true, updated_at = now();

create table if not exists public.historical_import_batches (
  id uuid primary key default gen_random_uuid(),
  created_by_driver_id uuid not null references public.drivers(id) on delete restrict,
  created_by_email text not null,
  source_name text not null default 'historical_screenshot_gpt',
  original_filename text not null,
  file_size_bytes bigint not null default 0 check (file_size_bytes >= 0),
  file_sha256 text,
  format text not null check (format in ('jsonl','json')),
  status text not null default 'receiving' check (status in ('receiving','staged','processing','ready','failed','archived')),
  received_count integer not null default 0 check (received_count >= 0),
  valid_count integer not null default 0 check (valid_count >= 0),
  partial_count integer not null default 0 check (partial_count >= 0),
  invalid_count integer not null default 0 check (invalid_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  constraint historical_import_batches_file_sha check (file_sha256 is null or file_sha256 ~ '^[a-f0-9]{64}$')
);

create table if not exists public.historical_import_rows (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.historical_import_batches(id) on delete cascade,
  row_index integer not null check (row_index >= 0),
  source_file_name text,
  source_file_sha256 text,
  semantic_key text not null,
  validation_status text not null check (validation_status in ('valid','partial','invalid','duplicate')),
  validation_errors jsonb not null default '[]'::jsonb,
  original_payload jsonb not null,
  normalized_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint historical_import_rows_batch_row_unique unique (batch_id,row_index),
  constraint historical_import_rows_file_sha check (source_file_sha256 is null or source_file_sha256 ~ '^[a-f0-9]{64}$')
);

create index if not exists historical_import_access_enabled_idx on public.historical_import_access(enabled,email);
create index if not exists historical_import_batches_created_idx on public.historical_import_batches(created_at desc);
create index if not exists historical_import_batches_creator_idx on public.historical_import_batches(created_by_driver_id,created_at desc);
create index if not exists historical_import_rows_batch_status_idx on public.historical_import_rows(batch_id,validation_status,row_index);
create index if not exists historical_import_rows_file_sha_idx on public.historical_import_rows(source_file_sha256) where source_file_sha256 is not null;
create index if not exists historical_import_rows_semantic_idx on public.historical_import_rows(semantic_key);

alter table public.historical_import_access enable row level security;
alter table public.historical_import_batches enable row level security;
alter table public.historical_import_rows enable row level security;

revoke all on table public.historical_import_access from public, anon, authenticated;
revoke all on table public.historical_import_batches from public, anon, authenticated;
revoke all on table public.historical_import_rows from public, anon, authenticated;
revoke all on sequence public.historical_import_rows_id_seq from public, anon, authenticated;

grant all on table public.historical_import_access to service_role;
grant all on table public.historical_import_batches to service_role;
grant all on table public.historical_import_rows to service_role;
grant usage, select on sequence public.historical_import_rows_id_seq to service_role;

comment on table public.historical_import_access is 'Allowlist Web-only para o portal interno de importacao historica do Sr. Rotas.';
comment on table public.historical_import_batches is 'Lotes de JSON/JSONL em staging; nao alimentam ride_offers diretamente.';
comment on table public.historical_import_rows is 'Linhas originais e normalizadas para validacao/deduplicacao antes do Context Engine.';

commit;
