package com.srrotas.app

import android.Manifest
import android.app.Activity
import android.content.*
import android.graphics.Color
import android.media.projection.MediaProjectionManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.Settings
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*

class MainActivity : Activity() {
    companion object { private const val REQ_MEDIA_PROJECTION=4101; private const val REQ_NOTIFICATIONS=4102 }
    private lateinit var repo:SettingsRepository;private lateinit var projectionManager:MediaProjectionManager
    private lateinit var backendInput:EditText;private lateinit var pairingInput:EditText;private lateinit var ocrCheck:CheckBox;private lateinit var consentCheck:CheckBox
    private lateinit var stopJourneyButton:Button;private lateinit var pairingStatus:TextView;private lateinit var latestSummary:TextView;private lateinit var latestRaw:TextView;private lateinit var serviceStatus:TextView;private lateinit var localHistory:TextView;private lateinit var strategySummary:TextView;private lateinit var aiQuestionInput:EditText;private lateinit var aiAnswer:TextView
    private val captureReceiver=object:BroadcastReceiver(){override fun onReceive(context:Context?,intent:Intent?){refreshStatus();refreshDiagnostics();refreshLocalHistory()}}

    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);repo=SettingsRepository(this);projectionManager=getSystemService(MediaProjectionManager::class.java);setContentView(buildUi());loadSettings()}
    override fun onResume(){super.onResume();registerCaptureReceiver();refreshStatus();refreshDiagnostics();refreshLocalHistory();refreshStrategy();BackendClient.flushPendingOffers(this)}
    override fun onPause(){runCatching{unregisterReceiver(captureReceiver)};super.onPause()}

    @Deprecated("Mantido sem AndroidX neste Alpha")
    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=REQ_MEDIA_PROJECTION)return;if(resultCode!=RESULT_OK||data==null){toast("A captura não foi autorizada.");return};val journey=JourneyCoordinator.startJourney(this);val intent=Intent(this,MediaProjectionOcrService::class.java).apply{action=MediaProjectionOcrService.ACTION_START;putExtra(MediaProjectionOcrService.EXTRA_RESULT_CODE,resultCode);putExtra(MediaProjectionOcrService.EXTRA_RESULT_DATA,data)};val failed=runCatching{if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O)startForegroundService(intent)else startService(intent)}.exceptionOrNull();if(failed!=null){JourneyCoordinator.endJourney(this,"service_start_failed");toast("Não foi possível iniciar: ${failed.message}");return};toast("Jornada ${journey.id.take(8)} iniciada. Abra o Uber Driver.");refreshStatus();refreshLocalHistory()}

    private fun buildUi():View{
        val scroll=ScrollView(this).apply{setBackgroundColor(Color.rgb(247,240,200))};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(20),dp(20),dp(44))};scroll.addView(root)
        root.addView(ImageView(this).apply{setImageResource(R.drawable.logo_srrotas);adjustViewBounds=true;scaleType=ImageView.ScaleType.CENTER_INSIDE},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(145)))
        root.addView(title("Sr. Rotas 2.0 Alpha",27f));root.addView(body("Seu copiloto inteligente para analisar ofertas em tempo real. A versão 0.5 reforça o Radar, evita duplicações alternadas, filtra a própria tela do Sr. Rotas e traz um HUD maior e mais limpo."));root.addView(body("Versão instalada: ${BuildConfig.VERSION_NAME}"));root.addView(space(14))

        root.addView(section("1. Jornada"));root.addView(body("A captura da tela é autorizada pelo Android a cada sessão. O OCR é local; o Sr. Rotas não aceita nem recusa corridas."));consentCheck=CheckBox(this).apply{text="Entendi e autorizo a análise local da tela durante minhas jornadas.";setOnCheckedChangeListener{_,_->saveBaseSettings()}};root.addView(consentCheck);serviceStatus=body("");root.addView(serviceStatus);root.addView(actionButton("Permitir HUD sobre outros apps"){openOverlayPermission()});root.addView(actionButton("▶ Iniciar jornada"){startJourney()});stopJourneyButton=actionButton("■ Encerrar jornada"){stopService(Intent(this,MediaProjectionOcrService::class.java));repo.setProjectionActive(false);JourneyCoordinator.endJourney(this,"user_stop");refreshStatus();refreshLocalHistory();toast("Jornada encerrada.")};root.addView(stopJourneyButton)
        localHistory=cardText();root.addView(localHistory)

        root.addView(space(18));root.addView(section("2. Estratégia e HUD"));strategySummary=cardText();root.addView(strategySummary);root.addView(actionButton("Abrir Estratégia e HUD"){startActivity(Intent(this,StrategyActivity::class.java))});root.addView(body("Configure faixas vermelho/amarelo/verde, R$/km, R$/hora, avaliação, R$/min, custos, lucro, ordem das métricas, posição, tema, opacidade, fonte, notificações e captura privada opcional."))

        root.addView(space(18));root.addView(section("3. Backend Sr. Rotas"));backendInput=textInput("URL do backend");pairingInput=textInput("Código de pareamento").apply{inputType=InputType.TYPE_CLASS_NUMBER};root.addView(backendInput);root.addView(pairingInput);root.addView(actionButton("Parear aparelho"){pairDevice()});pairingStatus=body("");root.addView(pairingStatus);root.addView(actionButton("Sincronizar pendências"){saveBaseSettings();BackendClient.syncPreferences(this);BackendClient.flushPendingOffers(this);toast("Sincronização solicitada.")})

        root.addView(space(18));root.addView(section("4. Pesquisa IA"));root.addView(body("Pergunte sobre ofertas observadas e sincronizadas. Oferta observada nunca é tratada automaticamente como corrida aceita ou concluída."));aiQuestionInput=EditText(this).apply{hint="Ex.: Em quais horários apareceram as melhores ofertas nesta semana?";minLines=2;maxLines=4;gravity=Gravity.TOP;setPadding(dp(12),dp(10),dp(12),dp(10));setBackgroundColor(Color.WHITE)};root.addView(aiQuestionInput);root.addView(actionButton("Perguntar à IA"){askAi()});aiAnswer=cardText();root.addView(aiAnswer)

        root.addView(space(18));root.addView(section("5. Diagnóstico"));root.addView(body("O diagnóstico registra o OCR e as ofertas locais para calibrar o Alpha. Screenshots privadas só existem se você ativar essa opção e nunca entram automaticamente no pacote textual."));latestSummary=title("",18f);root.addView(latestSummary);latestRaw=cardText().apply{textSize=12f};root.addView(latestRaw);root.addView(actionButton("Atualizar diagnóstico"){refreshDiagnostics();refreshLocalHistory()});root.addView(actionButton("Compartilhar diagnóstico (texto)"){DiagnosticBundle.share(this)})

        root.addView(space(18));root.addView(section("6. Leitura auxiliar — opcional"));root.addView(body("MediaProjection é o motor principal. A Acessibilidade deve ser usada somente como caminho auxiliar de diagnóstico quando necessária."));root.addView(actionButton("Abrir configurações de Acessibilidade"){saveBaseSettings();startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))});ocrCheck=CheckBox(this).apply{text="Permitir OCR auxiliar quando MediaProjection estiver desligado";setOnCheckedChangeListener{_,_->saveBaseSettings()}};root.addView(ocrCheck)
        root.addView(space(18));root.addView(section("Sobre"));root.addView(body("Sr. Rotas é desenvolvido pela BigCorps.\nSuporte: contato@bigcorps.com.br"));return scroll
    }

    private fun loadSettings(){val s=repo.load();backendInput.setText(s.backendUrl);ocrCheck.isChecked=s.ocrEnabled;consentCheck.isChecked=s.consentAccepted;pairingStatus.text=if(s.deviceToken.isBlank())"Aparelho ainda não pareado." else "✓ Aparelho pareado com o backend."}
    private fun saveBaseSettings(){val c=repo.load();repo.save(c.copy(backendUrl=if(::backendInput.isInitialized)backendInput.text.toString()else c.backendUrl,ocrEnabled=if(::ocrCheck.isInitialized)ocrCheck.isChecked else c.ocrEnabled,consentAccepted=if(::consentCheck.isInitialized)consentCheck.isChecked else c.consentAccepted))}
    private fun startJourney(){saveBaseSettings();if(!consentCheck.isChecked){toast("Marque o consentimento antes de iniciar.");return};if(!Settings.canDrawOverlays(this)){toast("Primeiro permita o HUD.");openOverlayPermission();return};requestNotificationPermissionIfNeeded();@Suppress("DEPRECATION") startActivityForResult(projectionManager.createScreenCaptureIntent(),REQ_MEDIA_PROJECTION)}
    private fun openOverlayPermission(){startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:$packageName")))}
    private fun requestNotificationPermissionIfNeeded(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.TIRAMISU&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),REQ_NOTIFICATIONS)}
    private fun pairDevice(){saveBaseSettings();pairingStatus.text="Pareando...";BackendClient.pair(this,backendInput.text.toString(),pairingInput.text.toString()){r->r.onSuccess{pairingStatus.text="✓ Aparelho pareado com sucesso.";pairingInput.setText("");BackendClient.syncPreferences(this);BackendClient.flushPendingOffers(this)}.onFailure{pairingStatus.text="Falha no pareamento: ${it.message}"}}}
    private fun askAi(){saveBaseSettings();aiAnswer.text="Consultando...";BackendClient.ask(this,aiQuestionInput.text.toString()){r->aiAnswer.text=r.fold({it},{"Falha: ${it.message}"})}}
    private fun refreshStrategy(){if(!::strategySummary.isInitialized)return;val s=repo.load();strategySummary.text="Verde: R$ ${fmt(s.minPerMinute)}/min · R$ ${fmt(s.minPerKm)}/km · R$ ${fmt(s.minPerHour)}/h · ★ ${fmt(s.goodRatingFrom)}\nVermelho abaixo: R$ ${fmt(s.redPerMinuteBelow)}/min · R$ ${fmt(s.redPerKmBelow)}/km · R$ ${fmt(s.redPerHourBelow)}/h · ★ ${fmt(s.redRatingBelow)}\nCusto estimado: R$ ${fmt(s.costPerKm)}/km · HUD ${s.hudPosition}/${s.hudTheme} · fonte ${s.hudFontSize}"}
    private fun refreshStatus(){val projection=repo.isProjectionActive();val overlay=Settings.canDrawOverlays(this);val accessibility=isAccessibilityServiceEnabled();val current=repo.currentJourneyId();serviceStatus.text=buildString{append(if(projection)"✓ Jornada ativa" else "○ Jornada parada");if(current.isNotBlank())append(" · ${current.take(8)}");append("\n");append(if(overlay)"✓ HUD autorizado" else "○ HUD sem permissão");append("\n");append(if(accessibility)"✓ Leitura auxiliar ativa" else "○ Leitura auxiliar desligada")};stopJourneyButton.isEnabled=projection||current.isNotBlank()}
    private fun refreshLocalHistory(){val store=LocalStore.get(this);val summary=JourneyCoordinator.currentSummary(this)?:store.latestJourney()?.let{store.journeySummary(it.id)};localHistory.text=buildString{if(summary==null)append("Histórico local: nenhuma jornada registrada.")else{append(if(summary.journey.endedAt==null)"Jornada atual" else "Última jornada");append(" · ${summary.journey.id.take(8)}\nOfertas válidas: ${summary.offerCount} · boas ${summary.goodCount} · atenção ${summary.regularCount} · ruins ${summary.badCount}");summary.averagePerKm?.let{append("\nMédia: R$ ${fmt(it)}/km")};summary.averagePerHour?.let{append(" · R$ ${fmt(it)}/h")}};append("\nPendentes: ${store.pendingOfferCount()} · Capturas privadas: ${PrivateScreenshotStore.count(this@MainActivity)}")}}
    private fun refreshDiagnostics(){latestSummary.text=repo.latestSummary();val method=repo.latestMethod().takeIf{it.isNotBlank()}?.let{"Método: $it\n\n"}?:"";val raw=repo.latestRaw();val log=LocalLog.tail(this,45);latestRaw.text=if(raw.isNotBlank())"$method$raw\n\n--- LOG LOCAL ---\n$log" else "Nenhum texto bruto capturado.\n\n--- LOG LOCAL ---\n$log"}
    private fun isAccessibilityServiceEnabled():Boolean{val expected="$packageName/${DriverAccessibilityService::class.java.name}";val enabled=Settings.Secure.getString(contentResolver,Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES)?:return false;return enabled.split(':').any{it.equals(expected,true)}}
    private fun registerCaptureReceiver(){val filter=IntentFilter(AppSignals.ACTION_CAPTURE_UPDATED);if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.TIRAMISU)registerReceiver(captureReceiver,filter,RECEIVER_NOT_EXPORTED)else{@Suppress("DEPRECATION") registerReceiver(captureReceiver,filter)}}
    private fun title(t:String,s:Float)=TextView(this).apply{text=t;textSize=s;setTextColor(Color.rgb(7,55,70));setPadding(0,0,0,dp(8))};private fun section(t:String)=title(t,20f);private fun body(t:String)=TextView(this).apply{text=t;textSize=15f;setTextColor(Color.rgb(45,70,72));setLineSpacing(0f,1.12f)};private fun cardText()=TextView(this).apply{textSize=14f;setTextColor(Color.rgb(7,55,70));setTextIsSelectable(true);setPadding(dp(12),dp(12),dp(12),dp(12));setBackgroundColor(Color.WHITE)};private fun textInput(h:String)=EditText(this).apply{hint=h;setSingleLine(true);setPadding(dp(12),dp(8),dp(12),dp(8));setBackgroundColor(Color.WHITE)};private fun actionButton(t:String,a:()->Unit)=Button(this).apply{text=t;isAllCaps=false;setOnClickListener{a()}};private fun space(h:Int)=Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,dp(h))};private fun fmt(v:Double)=String.format(java.util.Locale("pt","BR"),"%.2f",v);private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun toast(t:String)=Toast.makeText(this,t,Toast.LENGTH_SHORT).show()
}
