package com.srrotas.app

import android.Manifest
import android.app.Activity
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.Settings
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.CheckBox
import android.widget.EditText
import android.widget.FrameLayout
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import android.widget.Toast

/** 0.21 — onboarding curto: conta → permissões → estratégia → pronto. */
class OnboardingActivity : Activity() {
    companion object { private const val REQ_NOTIFICATIONS=7701; private const val REQ_LOCATION=7702 }
    private lateinit var repo:SettingsRepository;private lateinit var content:FrameLayout;private lateinit var progress:TextView;private var step=0
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);repo=SettingsRepository(this);UiKit.applySystemBars(this);step=repo.load().onboardingStep.coerceIn(0,3);val shell=buildShell();setContentView(shell);UiKit.applySafeArea(shell);render()}
    override fun onResume(){super.onResume();if(::content.isInitialized&&step==1)render()}
    private fun buildShell():View{val p=UiKit.palette(this);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(p.background)};root.addView(LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(10));setBackgroundColor(p.surface);addView(ImageView(this@OnboardingActivity).apply{setImageResource(R.drawable.logo_srrotas);scaleType=ImageView.ScaleType.CENTER_INSIDE},LinearLayout.LayoutParams(dp(48),dp(48)));addView(LinearLayout(this@OnboardingActivity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,0,0);addView(UiKit.title(this@OnboardingActivity,"Começar no Sr. Rotas",20f));progress=UiKit.body(this@OnboardingActivity,"",12f);addView(progress)},LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f))});content=FrameLayout(this);root.addView(content,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f));return root}
    private fun render(){content.removeAllViews();progress.text="Etapa ${step+1} de 4";val(scroll,root)=page();when(step){0->account(root);1->permissions(root);2->strategy(root);else->ready(root)};content.addView(scroll);repo.markOnboardingStep(step)}
    private fun account(root:LinearLayout){val s=repo.load();root.addView(UiKit.title(this,"Sua conta",28f));root.addView(UiKit.body(this,"Use a mesma conta no Android e na Web. Configurações avançadas ficam para depois."));if(s.deviceToken.isNotBlank()){root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.pill(this@OnboardingActivity,"APARELHO CONECTADO","good"));addView(UiKit.margin(UiKit.title(this@OnboardingActivity,s.driverDisplayName,20f),top=8));addView(UiKit.body(this@OnboardingActivity,s.accountEmail.ifBlank{"Sessão existente"}))},top=14));root.addView(UiKit.margin(UiKit.primaryButton(this,"Continuar"){next()},top=12));return}
      val email=UiKit.input(this,"E-mail").apply{inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS};val pass=UiKit.input(this,"Senha — mínimo 8 caracteres").apply{inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD};val name=UiKit.input(this,"Nome").apply{setText(s.driverDisplayName.takeUnless{it=="Motorista"}?:"")};root.addView(UiKit.margin(UiKit.card(this).apply{addView(name);addView(UiKit.margin(email,top=7));addView(UiKit.margin(pass,top=7));addView(UiKit.margin(UiKit.primaryButton(this@OnboardingActivity,"Criar conta"){val display=name.text.toString().trim().ifBlank{"Motorista"};BackendClient.registerAccount(this@OnboardingActivity,email.text.toString(),pass.text.toString(),display){it.onSuccess{toast("Conta criada.");next()}.onFailure{e->toast("Não foi possível criar: ${e.message}")}}},top=9));addView(UiKit.margin(UiKit.secondaryButton(this@OnboardingActivity,"Entrar"){BackendClient.loginAccount(this@OnboardingActivity,email.text.toString(),pass.text.toString()){it.onSuccess{toast("Aparelho conectado.");next()}.onFailure{e->toast("Não foi possível entrar: ${e.message}")}}},top=7))},top=14))}
    private fun permissions(root:LinearLayout){root.addView(UiKit.title(this,"Só o necessário",28f));root.addView(UiKit.body(this,"O HUD precisa aparecer sobre outros apps. A localização aproximada alimenta Agora e a inteligência de região. A captura da tela é autorizada pelo Android somente ao iniciar uma jornada."));val overlay=Settings.canDrawOverlays(this);val location=checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;val notifications=Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;root.addView(UiKit.margin(status("HUD",overlay,"Mostrar o Painel de Rota.","Permitir"){startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:$packageName")))},top=14));root.addView(UiKit.margin(status("Localização aproximada",location,"Sugestões de regiões próximas e exposição regional.","Permitir"){requestPermissions(arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION),REQ_LOCATION)},top=8));root.addView(UiKit.margin(status("Notificações",notifications,"Mantém a jornada e avisos operacionais.","Permitir"){if(Build.VERSION.SDK_INT>=33)requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),REQ_NOTIFICATIONS)},top=8));root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.pill(this@OnboardingActivity,"PRIVACIDADE","primary"));addView(UiKit.margin(UiKit.body(this@OnboardingActivity,"MediaProjection é pedido a cada jornada. Screenshot e OCR bruto não são enviados por padrão."),top=8))},top=8));root.addView(UiKit.margin(UiKit.primaryButton(this,"Continuar"){next()},top=12));root.addView(UiKit.margin(UiKit.secondaryButton(this,"Voltar"){back()},top=7))}
    private fun strategy(root:LinearLayout){val s=repo.load();root.addView(UiKit.title(this,"Já deixamos preparado",28f));root.addView(UiKit.body(this,"Popular é o ponto de partida recomendado. Se você trabalha mais com outra categoria, troque agora ou personalize depois."));root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.primaryButton(this@OnboardingActivity,"Popular"){StrategyPresets021.apply(this@OnboardingActivity,"popular");toast("Popular aplicado.")});addView(UiKit.margin(UiKit.secondaryButton(this@OnboardingActivity,"Conforto"){StrategyPresets021.apply(this@OnboardingActivity,"comfort");toast("Conforto aplicado.")},top=7));addView(UiKit.margin(UiKit.secondaryButton(this@OnboardingActivity,"Premium"){StrategyPresets021.apply(this@OnboardingActivity,"premium");toast("Premium aplicado.")},top=7));addView(UiKit.margin(UiKit.secondaryButton(this@OnboardingActivity,"Misturo categorias / personalizar"){startActivity(Intent(this@OnboardingActivity,Strategy021Activity::class.java))},top=7));addView(UiKit.margin(UiKit.body(this@OnboardingActivity,"Busca inicial recomendada: ${s.maxPickupKm} km / ${Strategy021Store.load(this@OnboardingActivity).maxPickupMinutes} min. Tudo é editável."),top=10))},top=14));root.addView(UiKit.margin(UiKit.primaryButton(this,"Continuar"){Preference021Sync.sync(this);next()},top=12));root.addView(UiKit.margin(UiKit.secondaryButton(this,"Voltar"){back()},top=7))}
    private fun ready(root:LinearLayout){val s=repo.load();val collective=CheckBox(this).apply{text="Quero participar da base coletiva";isChecked=s.collectiveStatsOptIn;setTextColor(UiKit.palette(this@OnboardingActivity).ink)};val terms=CheckBox(this).apply{text="Li e aceito os Termos de Uso e a Política de Privacidade";setTextColor(UiKit.palette(this@OnboardingActivity).ink)};root.addView(UiKit.title(this,"Pronto para dirigir",28f));root.addView(UiKit.body(this,"Seu trial de 7 dias só começa quando a primeira oferta válida for persistida. Não existe cobrança automática."));root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.pill(this@OnboardingActivity,"7 DIAS GRÁTIS","good"));addView(UiKit.margin(UiKit.title(this@OnboardingActivity,"Tudo liberado para testar",20f),top=8));addView(UiKit.body(this@OnboardingActivity,"Inclui 5 créditos temporários de IA. O contador não começa pela instalação nem pelo cadastro."));addView(UiKit.margin(collective,top=10));addView(UiKit.body(this@OnboardingActivity,"Contribui com dados anonimizados → acessa a comunidade. A Base Sr. Rotas histórica agregada fica disponível para todos."));addView(UiKit.margin(terms,top=10));addView(UiKit.margin(UiKit.secondaryButton(this@OnboardingActivity,"Ler Termos de Uso"){startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://srrotas.com/termos")))},top=8));addView(UiKit.margin(UiKit.secondaryButton(this@OnboardingActivity,"Ler Política de Privacidade"){startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://srrotas.com/privacidade")))},top=6))},top=14));root.addView(UiKit.margin(UiKit.primaryButton(this,"Concluir configuração"){if(!terms.isChecked){toast("Aceite os Termos e a Política de Privacidade para continuar.");return@primaryButton};repo.save(repo.load().copy(collectiveStatsOptIn=collective.isChecked));repo.completeOnboarding();Preference021Sync.sync(this);BackendClient.updateAccountProfile(this,repo.load().driverDisplayName,true);setResult(RESULT_OK);finish()},top=12));root.addView(UiKit.margin(UiKit.secondaryButton(this,"Abrir versão Web"){WebHandoff021.open(this@OnboardingActivity,"/app")},top=7));root.addView(UiKit.margin(UiKit.secondaryButton(this,"Voltar"){back()},top=7))}
    private fun status(title:String,ok:Boolean,help:String,actionLabel:String,action:()->Unit):View=UiKit.card(this).apply{addView(UiKit.pill(this@OnboardingActivity,if(ok)"PRONTO" else "PENDENTE",if(ok)"good" else "warn"));addView(UiKit.margin(UiKit.title(this@OnboardingActivity,title,18f),top=7));addView(UiKit.body(this@OnboardingActivity,help));if(!ok)addView(UiKit.margin(UiKit.primaryButton(this@OnboardingActivity,actionLabel,action),top=8))}
    private fun page():Pair<ScrollView,LinearLayout>{val scroll=ScrollView(this).apply{isFillViewport=true};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(18),dp(16),dp(28));setBackgroundColor(UiKit.palette(this@OnboardingActivity).background)};scroll.addView(root);return scroll to root}
    private fun next(){step=(step+1).coerceAtMost(3);render()};private fun back(){step=(step-1).coerceAtLeast(0);render()};private fun dp(v:Int)=UiKit.dp(this,v);private fun toast(t:String)=Toast.makeText(this,t,Toast.LENGTH_SHORT).show()
}
