package com.srrotas.app

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.CheckBox
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.Spinner
import android.widget.TextView
import android.widget.Toast

class Strategy021Activity : Activity() {
    private val repo by lazy { SettingsRepository(this) }
    private lateinit var km:EditText;private lateinit var minutes:EditText;private lateinit var theme:Spinner;private lateinit var hudTheme:Spinner;private lateinit var collective:CheckBox;private lateinit var summary:TextView
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);UiKit.applySystemBars(this);val scroll=ScrollView(this);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(UiKit.dp(this@Strategy021Activity,16),UiKit.dp(this@Strategy021Activity,16),UiKit.dp(this@Strategy021Activity,16),UiKit.dp(this@Strategy021Activity,30));setBackgroundColor(UiKit.palette(this@Strategy021Activity).background)};scroll.addView(root);setContentView(scroll);UiKit.applySafeArea(scroll)
      root.addView(UiKit.title(this,"Estratégia",28f));root.addView(UiKit.body(this,"Perfis servem como ponto de partida e funcionam entre plataformas. Qualquer valor pode ser personalizado."));summary=UiKit.body(this,"",13f);root.addView(UiKit.margin(summary,top=10))
      root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.sectionTitle(this@Strategy021Activity,"Perfil de serviço"));addView(UiKit.primaryButton(this@Strategy021Activity,"Popular"){apply("popular")});addView(UiKit.margin(UiKit.secondaryButton(this@Strategy021Activity,"Conforto"){apply("comfort")},top=6));addView(UiKit.margin(UiKit.secondaryButton(this@Strategy021Activity,"Premium"){apply("premium")},top=6));addView(UiKit.margin(UiKit.secondaryButton(this@Strategy021Activity,"Personalizar métricas e Painel de Rota"){Strategy021Store.savePreset(this@Strategy021Activity,"custom");startActivity(Intent(this@Strategy021Activity,StrategyActivity::class.java))},top=8))},top=14))
      val s=repo.load();val x=Strategy021Store.load(this);km=UiKit.input(this,"Busca máxima em km — 0 desativa",numeric=true).apply{setText(s.maxPickupKm.toString())};minutes=UiKit.input(this,"Busca máxima em minutos — 0 desativa",numeric=true).apply{setText(x.maxPickupMinutes.toString())};root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.sectionTitle(this@Strategy021Activity,"Limites para buscar o passageiro"));addView(km);addView(UiKit.margin(minutes,top=7));addView(UiKit.body(this@Strategy021Activity,"Exceder quilômetros OU minutos rebaixa a oferta para abaixo da meta. Se um dado não estiver disponível, usamos somente o outro."))},top=12))
      theme=Spinner(this).apply{adapter=ArrayAdapter(this@Strategy021Activity,android.R.layout.simple_spinner_dropdown_item,listOf("Automático","Claro","Escuro"));setSelection(when(x.appTheme){"light"->1;"dark"->2;else->0})};hudTheme=Spinner(this).apply{adapter=ArrayAdapter(this@Strategy021Activity,android.R.layout.simple_spinner_dropdown_item,listOf("Seguir aplicativo","Claro","Escuro"));setSelection(when(x.hudThemeMode){"light"->1;"dark"->2;else->0})};collective=CheckBox(this).apply{text="Participar da base coletiva";isChecked=s.collectiveStatsOptIn;setTextColor(UiKit.palette(this@Strategy021Activity).ink)};root.addView(UiKit.margin(UiKit.card(this).apply{addView(UiKit.sectionTitle(this@Strategy021Activity,"Aparência e inteligência"));addView(UiKit.body(this@Strategy021Activity,"Tema do aplicativo"));addView(theme);addView(UiKit.margin(UiKit.body(this@Strategy021Activity,"Tema do HUD/menu"),top=8));addView(hudTheme);addView(UiKit.margin(collective,top=8));addView(UiKit.body(this@Strategy021Activity,"Contribui com dados anonimizados → acessa a comunidade. A Base Sr. Rotas histórica agregada continua disponível para todos."))},top=12))
      root.addView(UiKit.margin(UiKit.primaryButton(this,"Salvar"){save()},top=14));root.addView(UiKit.margin(UiKit.secondaryButton(this,"Abrir versão Web"){openWeb()},top=8));root.addView(UiKit.margin(UiKit.secondaryButton(this,"Voltar"){finish()},top=8));refreshSummary()
    }
    override fun onResume(){super.onResume();if(::summary.isInitialized)refreshSummary()}
    private fun apply(p:String){StrategyPresets021.apply(this,p);refreshSummary();Preference021Sync.sync(this);Toast.makeText(this,"${name(p)} aplicado. Limites de busca foram preservados.",Toast.LENGTH_SHORT).show()}
    private fun save(){val s=repo.load();val maxKm=km.text.toString().replace(',','.').toDoubleOrNull()?.coerceIn(0.0,100.0)?:s.maxPickupKm;val maxMin=minutes.text.toString().toIntOrNull()?.coerceIn(0,120)?:8;val appTheme=when(theme.selectedItemPosition){1->"light";2->"dark";else->"auto"};repo.save(s.copy(maxPickupKm=maxKm,collectiveStatsOptIn=collective.isChecked));Strategy021Store.saveMaxPickupMinutes(this,maxMin);Strategy021Store.saveAppTheme(this,appTheme);val hm=when(hudTheme.selectedItemPosition){1->"light";2->"dark";else->"follow_app"};Strategy021Store.saveHudThemeMode(this,hm);val resolvedHud=when(hm){"light"->"light";"dark"->"dark";else->appTheme};repo.save(repo.load().copy(hudTheme=resolvedHud));if(Strategy021Store.load(this).strategyPreset!="custom"&&!matchesPreset(repo.load(),Strategy021Store.load(this).strategyPreset))Strategy021Store.savePreset(this,"custom");BackendClient.syncPreferences(this);Preference021Sync.sync(this);Toast.makeText(this,"Estratégia salva.",Toast.LENGTH_SHORT).show();recreate()}
    private fun refreshSummary(){val s=repo.load();var x=Strategy021Store.load(this);if(x.strategyPreset!="custom"&&!matchesPreset(s,x.strategyPreset)){Strategy021Store.savePreset(this,"custom");x=Strategy021Store.load(this)};summary.text="${name(x.strategyPreset)} · R$ ${f(s.redPerKmBelow)}→${f(s.minPerKm)}/km · R$ ${f(s.redPerMinuteBelow)}→${f(s.minPerMinute)}/min · R$ ${f(s.redPerHourBelow)}→${f(s.minPerHour)}/h\nBusca máxima: ${f(s.maxPickupKm)} km / ${x.maxPickupMinutes} min"}
    private fun matchesPreset(s:DriverSettings,p:String):Boolean=when(p){"popular"->s.redPerKmBelow==1.2&&s.minPerKm==1.5&&s.redPerMinuteBelow==.4&&s.minPerMinute==.5&&s.redPerHourBelow==24.0&&s.minPerHour==30.0;"comfort"->s.redPerKmBelow==1.5&&s.minPerKm==1.8&&s.redPerMinuteBelow==.5&&s.minPerMinute==.65&&s.redPerHourBelow==30.0&&s.minPerHour==39.0;"premium"->s.redPerKmBelow==1.8&&s.minPerKm==2.2&&s.redPerMinuteBelow==.65&&s.minPerMinute==.85&&s.redPerHourBelow==39.0&&s.minPerHour==51.0;else->false}
    private fun name(p:String)=when(p){"popular"->"Popular";"comfort"->"Conforto";"premium"->"Premium";else->"Personalizado"};private fun f(v:Double)=String.format(java.util.Locale("pt","BR"),"%.2f",v)
    private fun openWeb(){WebHandoff021.open(this,"/app/perfil")}
}
