"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
type Me={display_name:string;email:string;onboarding_completed:boolean;legacy:boolean};
type Billing={plan?:{name?:string;amount_cents?:number};subscription:null|{active:boolean;status:string;current_period_end:string|null};trial?:{trial_status:"pending"|"active"|"expired";days_remaining:number|null};wallet:{balance:number}};
type Device={id:string;name:string;revoked:boolean;last_seen_at:string|null;created_at:string};type Devices={devices:Device[];active_count:number;max_active_devices:number;note?:string};
function when(v?:string|null){return v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"Nunca";}
export default function PerfilPage(){const router=useRouter();const[me,setMe]=useState<Me|null>(null);const[billing,setBilling]=useState<Billing|null>(null);const[devices,setDevices]=useState<Devices|null>(null);
 useEffect(()=>{Promise.all([fetch("/api/v1/account/me",{cache:"no-store"}).then(r=>r.ok?r.json():null),fetch("/api/v1/billing/status",{cache:"no-store"}).then(r=>r.ok?r.json():null),fetch("/api/v1/account/devices",{cache:"no-store"}).then(r=>r.ok?r.json():null)]).then(([a,b,d])=>{setMe(a);setBilling(b);setDevices(d)}).catch(()=>undefined)},[]);
 const initials=useMemo(()=>{const n=(me?.display_name||"Sr. Rotas").trim().split(/\s+/).filter(Boolean);return (n[0]?.[0]||"S")+(n.length>1?n[n.length-1][0]:"")},[me]);
 const planLabel=billing?.subscription?.active?"Ativo":billing?.trial?.trial_status==="active"?"Teste":"Sem assinatura";
 const price=billing?.plan?.amount_cents!=null?`R$ ${(billing.plan.amount_cents/100).toLocaleString("pt-BR",{minimumFractionDigits:2})}/mês`:null;
 async function logout(){await fetch("/api/v1/billing/web-logout",{method:"POST"}).catch(()=>undefined);router.replace("/");router.refresh();}
 return <div className="sr023Page sr023User"><section className="sr023Hero"><div><h1>Usuário</h1><p>Conta, plano, créditos, aparelhos e segurança.</p></div><article className="sr023Identity"><div className="sr023Avatar">{initials}</div><div><strong>{me?.display_name??"Carregando…"}</strong><span>{me?.email??""}</span><small>● Conta online</small></div></article></section>
 <section className="sr023Plan"><div><h2>Plano e créditos</h2><article><div><strong>{billing?.plan?.name||"Sr. Rotas"}</strong><span>{planLabel}</span>{price?<small>{price}</small>:null}</div><div><small>Créditos de IA</small><b>{billing?.wallet?.balance??"—"}</b><span>disponíveis</span></div></article><Link href="/app/plano">Gerenciar plano</Link></div></section>
 <section className="sr023Grid"><Link className="sr023Tile" href="#conta"><i className="blue">▣</i><div><h2>Dados da conta</h2><p>Nome, e-mail e cadastro</p></div><b>›</b></Link><a className="sr023Tile" href="#aparelhos"><i className="teal">▱</i><div><h2>Aparelhos</h2><p>{devices?`${devices.active_count} conectado(s) de ${devices.max_active_devices}`:"Carregando…"}</p></div><b>›</b></a><Link className="sr023Tile" href="/app/inicio"><i className="purple">⌾</i><div><h2>Configuração da conta</h2><p>Revise seus dados e vínculo da conta</p></div><b>›</b></Link><Link className="sr023Tile" href="/app/plano"><i className="orange">▤</i><div><h2>Assinatura</h2><p>Pagamentos e histórico</p></div><b>›</b></Link><Link className="sr023Tile" href="/app/perfil/mensagens"><i className="teal">✉</i><div><h2>Mensagens rápidas</h2><p>Configure os atalhos 1–6 da janela flutuante</p></div><b>›</b></Link></section>
 <section id="aparelhos" className="sr023Panel"><h2>Aparelhos</h2>{devices?.devices?.length?devices.devices.map(d=><div className="sr023Device" key={d.id}><span>▱</span><div><strong>{d.name}</strong><small>Último contato: {when(d.last_seen_at)}</small></div><b className={d.revoked?"bad":"good"}>{d.revoked?"Revogado":"Ativo"}</b></div>):<p>Nenhum aparelho encontrado.</p>}</section>
 <section className="sr023Panel"><h2>Acesso e segurança</h2><Link className="sr023Security" href="/app/mcp"><span>◇</span><div><strong>Segurança MCP</strong><small>Chaves e revogação</small></div><b>›</b></Link><button className="sr023Security" onClick={logout}><span>↪</span><div><strong>Sair desta conta Web</strong><small>Encerra somente esta sessão do navegador</small></div><b>›</b></button><a className="sr023Security danger" href="/excluir-conta"><span>♙</span><div><strong>Excluir minha conta e dados</strong><small>Esta ação exige confirmação.</small></div><b>›</b></a></section></div>;
}
